export const addNewPlace = async (req, res, next) => {
  try {
  } catch (err) {
    return res.status(500).json({
      message: "Internal Server Error!",
      error: err.message,
    });
  }
};
